### ISSUE TITLE
HUB error exception

### ISSUE THREAD

**Issue by nyok92** [immstudios/nebula-hub#1]
**Hello, i do have an error when connecting firefly to nebula server.
I do have clones nebula and nebula-setup from immstudios and follow steps for install.
I have on full nebula server and one ohter machine for casparcg. I share a smb from casparcg to my nebula server.
I see all my files in assets on firefly and on website.
When i start firefly, i've got this error : unable to load playout plugins, unable to connect to the playout service
Here are the logs of /manage.py run hub:**

2021-03-02 15:41:51 INFO        hub             Reloading webtools
2021-03-02 15:41:51 INFO        hub             Reloading API methods
2021-03-02 15:41:51 GOOD NEWS   hub             Web service started
2021-03-02 15:41:58 DEBUG       hub             Executing get query: SELECT id, meta, 0 FROM assets WHERE id_folder IN (1,2) AND status IN (0,1,2,5,11) ORDER BY id desc LIMIT 101
2021-03-02 15:42:01 INFO        hub             audio requested api method jobs
2021-03-02 15:42:04 DEBUG       hub             Executing get query: SELECT id, meta, 0 FROM assets WHERE id_folder IN (1,2) AND status IN (0,1,2,5,11) ORDER BY id desc LIMIT 101
2021-03-02 15:42:18 WARNING     hub             PING: Not logged in - session ab4fa29bbc2735079cd77c0d907c6b6d5543f742d4735e332cf999200cb8e3be not found
2021-03-02 15:42:25 GOOD NEWS   hub             User audio logged in
2021-03-02 15:42:25 INFO        hub             audio requested api method settings
2021-03-02 15:42:25 INFO        hub             audio requested api method schedule
2021-03-02 15:42:25 DEBUG       hub             Requested events of channel 1 from 2021-03-01 07:00:00 to 2021-03-08 07:00:00
2021-03-02 15:42:25 INFO        hub             audio requested api method get
2021-03-02 15:42:25 DEBUG       hub             Executing get query: SELECT id, meta, 0 FROM assets WHERE id_folder IN (5,6,7,8) AND status IN (0,1,2,5,11) ORDER BY meta->>'title' asc LIMIT 1001
2021-03-02 15:42:25 INFO        hub             audio requested api method rundown
2021-03-02 15:42:25 INFO        hub             audio requested api method playout
2021-03-02 15:42:25 ERROR       hub             Exception!

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
        httplib_response = self._make_request(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
        six.raise_from(e, None)
      File "<string>", line 3, in raise_from
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
        response.begin()
      File "/usr/lib/python3.8/http/client.py", line 307, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
        raise RemoteDisconnected("Remote end closed connection without"
    http.client.RemoteDisconnected: Remote end closed connection without response
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
        resp = conn.urlopen(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
        retries = retries.increment(
      File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
        httplib_response = self._make_request(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
        six.raise_from(e, None)
      File "<string>", line 3, in raise_from
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
        response.begin()
      File "/usr/lib/python3.8/http/client.py", line 307, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
        raise RemoteDisconnected("Remote end closed connection without"
    urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
    
    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/nebula/nx/api/playout.py", line 57, in api_playout
        response = requests.post(controller_url + "/" + action, timeout=4, data=kwargs)
      File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
        return request('post', url, data=data, json=json, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
    

2021-03-02 15:42:25 ERROR       hub             API Request 'playout' by audio failed with code  502 Unable to connect to the playout service

**and here are the logs for ./nebula.py**

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53080)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/opt/nebula/services/play/request_handler.py", line 53, in do_POST
    postvars = cgi.parse_qs(self.rfile.read(length), keep_blank_values=1)
AttributeError: module 'cgi' has no attribute 'parse_qs'
----------------------------------------

Thanks !

**Comment by martastain** [comment]
Well... this is awkward. It is actually an error in the play service. That piece of code was there for ages and for ages cgi.parse_qs is deprecated. I wonder, why it worked in my dev setup, but hopefuly it is fixed now in https://github.com/immstudios/nebula/commit/6481a80bd079932a862e16074882191b62737d8e

**Comment by nyok92** [comment]
Thanks it's working now.
